- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ mysql_container_image }}"
    source: pull
    force_source: true

- name: Create container
  community.docker.docker_container:
    name: "{{ mysql_container_name }}"
    image: "{{ mysql_container_image }}"
    recreate: yes
    restart: true
    restart_policy: on-failure
    restart_retries: 20
    exposed_ports:
      - 3306 
    ports:
      - "3306:3306" 
    volumes:
      - "{{ mysql_volume_path }}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}" 
    networks:
      - name: "{{ common_network_name }}"
    capabilities:
      - sys_nice 
