- import_tasks: ufw-setup.yml

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ redis_container_image }}"
    source: pull
    force_source: true

- name: Create container
  community.docker.docker_container:
    name: "{{ redis_container_name }}"
    image: "{{ redis_container_image }}"
    command: redis-server
    recreate: yes
    restart: true
    restart_policy: on-failure
    restart_retries: 20
    exposed_ports:
      - 6379 
    ports:
      - "6379:6379" 
