- name: Print the info 
  ansible.builtin.debug:
    msg: image {{ container_image }} container {{ container_name }}
    verbosity: 1

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ container_image }}"
    source: pull
    force_source: true

- name: Copy docker compose yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /tmp/docker-compose.yml

- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: api-server 
    compose:
      - /tmp/docker-compose.yml
    prune: true
    with_registry_auth: true
  environment:
    DATABASE_URL: "{{ database_url }}"
    JWT_SECRET: "{{ jwt_secret }}"
    SIB_KEY: "{{ sib_key }}"
    REPLICAS: "{{ api_replicas }}"
    CONTAINER_IMAGE: "{{ container_image }}"

- name: post deploy 
  community.docker.docker_container:
    name: api-server-post-script 
    image: "{{ container_image }}"
    restart: true
    restart_policy: on-failure
    restart_retries: 20
    recreate: yes
    command: npm run db:deploy
    env:
      DATABASE_URL: "{{ database_url }}"
      JWT_SECRET: "{{ jwt_secret }}"
      SIB_KEY: "{{ sib_key }}"

- name: Prune everything
  community.docker.docker_prune:
    images: yes
    volumes: yes
    containers: yes
