- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg: image {{ container_image }} container {{ container_name }}
    verbosity: 1

- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ container_image }}"
    source: pull
    force_source: true

- name: Create default containers
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    recreate: yes
    exposed_ports:
      - 3000 
    ports:
      - "3000:3000" 

- name: Prune everything
  community.docker.docker_prune:
    images: yes
    volumes: yes
