- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ container_image }}"
    source: pull
    force_source: true

- name: Create default containers
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    recreate: yes
    exposed_ports:
      - 3000 
    ports:
      - "3000:3000" 

- name: Prune everything
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes
