- name: Debug
  debug: 
    msg: "The script file name is {{ script_name }}"

- name: run the job 
  community.docker.docker_container:
    name: "api-server-migration-{{ script_name }}" 
    image: "{{ container_image }}"
    restart: true
    restart_policy: on-failure
    restart_retries: 5 
    recreate: yes
    command: "node data/{{ script_name }}.js"
    env:
      DATABASE_URL: "{{ database_url_long_running }}"
      JWT_SECRET: "{{ jwt_secret }}"
      REDIS_URL: "{{ redis_url }}"
      DO_ACCESS_KEY: "{{ doAccessKey }}"
      DO_SECRET: "{{ doSecret }}"
      SENDGRID_API_KEY: "{{ sendgrid_key }}"
      SENDGRID_SANDBOX_MODE: '"{{ sendgrid_sandbox_mode }}"'
    log_driver: loki
    log_options:
      loki-url: "{{ loki_endpoint }}/loki/api/v1/push" 
      loki-pipeline-stages: |
        - json:
            expressions: 
              level: level
        - labels:
            level:

- name: Prune everything
  community.docker.docker_prune:
    images: yes
    volumes: yes
    containers: yes
