#- name: Install Python Module
  #pip:
    #name: 
      #- mysqlclient

- name: Create database user with readonly privilege 
  community.mysql.mysql_user:
    login_password: "{{ mysql_root_password }}"
    login_user: root
    name: "{{ mysql_readonly_username }}" 
    password: "{{ mysql_readonly_password }}" 
    host: '%'
    priv: "{{ mysql_database }}.*:SHOW VIEW"
    state: present
