name: API Deployment
on: 
  workflow_dispatch:
    inputs:
      deployEnv:
        description: 'env to deploy'     
        required: true
        default: 'staging' 
        type: choice
        options:
        - staging 
        - production 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create secrets directory
        run: |
          mkdir $HOME/secrets

      - name: render password file
        run: |
          echo $COMMON_PASSWORD > $HOME/secrets/common_password
        env:
          COMMON_PASSWORD: ${{ secrets.COMMON_PASSWORD }}

      - name: decrypt private_key
        run: |
          ansible-vault decrypt --vault-id $HOME/secrets/common_password secret_file/$DEPLOY_ENV/private_key.enc --output=$HOME/secrets/my_private_key.pem
        env:
          DEPLOY_ENV: ${{ github.event.inputs.deployEnv }}

      - name: touch
        run: |
          ansible-playbook -i inventories/$DEPLOY_ENV --vault-id $HOME/secrets/common_password -e="image_tag=main" -u root --private-key $HOME/secrets/my_private_key.pem apiserver.yml 
        env:
          DEPLOY_ENV: ${{ github.event.inputs.deployEnv }}
