name: notification test 
on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'tag to deploy'     
        required: true
        default: 'hello' 
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        uses: Ilshidur/action-discord@0.3.2
        with:
          #args: 'The project {{ REPO_NAME }} has been deployed. And, {{ MESSAGE }}'
          args: 'The project has been deployed. '
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE: ${{ github.event.inputs.message }}
          REPO_NAME: ${{ github.event.repo.name }}
