name: notification test 
on: 
  workflow_dispatch:

env:
  PROJECT_NAME: field-seating-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pre notification 
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '{{ PROJECT_NAME }} deployment has been started. Please refer to Run URL'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE: ${{ github.event.inputs.message }}
          DISCORD_EMBEDS: '[{"title": "Run #${{github.run_id}}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]'

      - name: post notification 
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '{{ PROJECT_NAME }} deployment was succussful. Please refer to Run URL'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE: ${{ github.event.inputs.message }}
          DISCORD_EMBEDS: '[{"title": "Run #${{github.run_id}}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]'

      - name: Try to fail
        run: exit 1

      - name: failure notification 
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '{{ PROJECT_NAME }} deployment was failed. Please refer to Run URL'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MESSAGE: ${{ github.event.inputs.message }}
          DISCORD_EMBEDS: '[{"title": "Run #${{github.run_id}}", "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}]'

