name: Scheduled MySQL Backup Staging 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch the backup action
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'field-seating',
              repo: 'devops-ansible',
              workflow_id: 'mysql-backup.yml',
              ref: 'main',
              inputs: {
                deployEnv: 'staging'
              }
            })
